name: Validate DAB Bundle

on:
  pull_request:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'prod' || (github.base_ref == 'dev' && 'dev') }}
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      ENV: ${{ vars.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Run Databricks CLI with debug
        run: databricks --debug current-user me

      - name: Validate bundle
        run: databricks bundle validate -t $ENV
